version: '3.8'
services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api 
    restart: always
    ports:
      - 3001:3001
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:10
    container_name: postgresprisma
    restart: always
    ports:
      - 5433:5433
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-prisma-docker-db